"""Add lock info to Games.

Revision ID: b65c12e7bf53
Revises: 5c35cb46dba5
Create Date: 2021-11-08 22:33:15.145925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65c12e7bf53'
down_revision = '5c35cb46dba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lock', sa.Boolean(), nullable=True))
    op.execute("UPDATE games SET lock = false")
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('lock', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('lock')

    # ### end Alembic commands ###
